### ISSUE TITLE
Using * to mask the digits

### ISSUE THREAD

**Issue by pierrederuel** [Brainants/pin_code_view#1]
Hi,

Thanks for your work, it's really great!

Could you add an attribute where we can hide the numbers of the code and replace them with another character? For example, 1234 would be ****

Thanks

**Comment by awazgyawali** [comment]
Great idea, will push an update when I get some time.

**Comment by awazgyawali** [comment]
Released v0.1.0 here https://github.com/awazgyawali/pin_code_view/commit/d52951f9e3c3acbaa903099def08870a699a5f1d

**Comment by pierrederuel** [comment]
That was fast! Thanks a lot 👍
