### ISSUE TITLE
Add letters on pin buttons for easier memorization

### ISSUE THREAD

**Issue by MateusRodCosta** [Brainants/pin_code_view#7]
Hi, it seems some users are used to having letters on the buttons and use them to memorize theirs pins.

Would it be possible to include this feature? I have a working implementation that I would like to upstream, but I think it would still needs some changes.

**Comment by Dshosev** [comment]
Hej @MateusRodCosta, I will look into this plugin anyway, so I will try to add your requested feature as an option, if that's okay for @awazgyawali.
I will fork this today and start working on some minor things, I encountered.

With that said, huge should out to @awazgyawali for this repo, it saved me a ton of work in the first place 😄

**Comment by awazgyawali** [comment]
@Dshosev The request seems to be valid enough. Please go ahead and do whatever you can to make the plugin more useful. I have no issues with it.
